### PR TITLE
Two more Tvshows added

### PR DESCRIPTION
**Pull request by mariaarcena**
After updated from master, I did not touch the test.json that had new things. I just left it as is and added the tv shows "Atlanta" and "Scream Queens"

Then I made it run through the test, they all passed!

Then I did the Debug, and wow! It alphabetized the tv show list; was that recent or did I not notice before? My gosh.

### CODE REVIEW

**Comment by joeyfreeman** [comment]
Are the first two episodes in Season 1 of Scream Queens supposed to have the same summary?

**Comment by allanhaywood** [comment]
@mariaarcena The sorting of the tvShow list is fairly new, I added it when I fixed the sorting of seasons and episodes. Also, comments and reviews should be sorted by date, but I haven't tested that out yet.

**Comment by mariaarcena** [comment]
@joeyfreeman Yes, that is correct. I was confused but I just pasted what was there!

**Review by joeyfreeman — APPROVED** [review]
Pulled branch and saw the new shows. Clicked through the episodes and didn't notice any issues

**Pull request merged**
