### PR TITLE
Master database manager

### PR DESCRIPTION
**Pull request by allanhaywood**
This includes the UML for database manager (this branch will remain open after merge for continued work).

In addition a basic TvShow class has been added (super basic), along with an example of a unit test.

The main reason I wanted to get this into master as soon as possible, is that, in order to add unit tests, there was some re-structuring.

There are a few different ways to handle unit tests, either keep them in a separate project (which I tried, and had issues), or keep them in the same project, as seen here. There are probably other options I didn't come across.

In any case, there is a working example of unit tests.

In order to execute unit tests, each user will need to add a new build type for test.

I essentially used instructions found here: http://xilexio.org/?p=125 with some modifications.

Please pull this branch and test out on your own, so we can address any issues before merging.

NOTE: I am including everyone due to the importance of unit tests and re-structuring, please try this out on your own. The only part you should have to do on your own is adding the test build config. Skip to "Lets create a new Build Configuration" at http://xilexio.org/?p=125

### CODE REVIEW

**Review by haleyminshell — APPROVED** [review]
I was able to run the unit test and all the tests passed. Looks good for the start of the tvshow class as well.

**Comment by joeyfreeman** [comment]
As discussed in class, we're going to wait to merge these changes. Allan is going to pull the recent updates from master, change the folder structure, and create a new pull request.

Edit: Master branch now contains updated dashboard and pages

**Comment by allanhaywood** [comment]
I have merged master into this branch.
Joey could you take a look and let me know if you approve?

**Review by joeyfreeman — APPROVED** [review]
Tested on my machine - everything works!

**Comment by haleyminshell** [comment]
I pulled down the latest changes and everything works for me also, including the unit tests. Looking good!

**Pull request merged**
